# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ai9Zz3fs0nOcueff8kg4mw8GFRTyiRBH
"""

import streamlit as st
import joblib
import numpy as np

# =========================
# Load Model & Preprocessing
# =========================
# Pastikan file "model_asd.pkl" dan "scaler.pkl" ada di folder yang sama
model = joblib.load("model_asd.pkl")
scaler = joblib.load("scaler.pkl")  # jika kamu pakai scaler

# =========================
# Judul Aplikasi
# =========================
st.title("Prediksi Autism Spectrum Disorder (ASD)")

st.markdown("""
Aplikasi ini menggunakan model Machine Learning untuk memprediksi kemungkinan **Autism Spectrum Disorder (ASD)** berdasarkan input pengguna.
""")

# =========================
# Input dari Pengguna
# =========================
st.subheader("Masukkan Data Pasien")

age = st.number_input("Umur", min_value=1, max_value=100, value=25)

gender = st.selectbox("Jenis Kelamin", ["Laki-laki", "Perempuan"])
jaundice = st.selectbox("Riwayat Jaundice", ["Ya", "Tidak"])
family_history = st.selectbox("Riwayat ASD di keluarga", ["Ya", "Tidak"])

# (Tambahkan variabel lain sesuai dataset yang kamu gunakan di notebook)
# Misalnya: result dari kuesioner, skor screening, dll.

# =========================
# Konversi Input ke Numerik
# =========================
# Pastikan sesuai preprocessing di notebook kamu
gender_num = 1 if gender == "Laki-laki" else 0
jaundice_num = 1 if jaundice == "Ya" else 0
family_num = 1 if family_history == "Ya" else 0

# Buat array input (contoh dengan 4 fitur, sesuaikan dengan datasetmu!)
input_data = np.array([[age, gender_num, jaundice_num, family_num]])

# Scaling jika model pakai scaler
input_scaled = scaler.transform(input_data)

# =========================
# Prediksi
# =========================
if st.button("Prediksi"):
    prediction = model.predict(input_scaled)
    proba = model.predict_proba(input_scaled)[0][1] if hasattr(model, "predict_proba") else None

    if prediction[0] == 1:
        st.error("Hasil Prediksi: **Berpotensi ASD**")
    else:
        st.success("Hasil Prediksi: **Tidak ASD**")

    if proba is not None:
        st.write(f"Tingkat Probabilitas: {proba:.2f}")