# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s6jmam8gOAjh0z8Pj6huLs-ygIjS4Icr
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib

# Menggunakan cache untuk model agar hanya di-load sekali
@st.cache_resource
def load_model():
    """
    Memuat pipeline model dan preprocessor yang sudah disimpan.
    """
    try:
        model_data = joblib.load('svm_model.joblib')
        return model_data
    except FileNotFoundError:
        return None

def main():
    st.set_page_config(page_title="Prediksi ASD pada Balita", layout="wide")
    st.title("👶 Prediksi Spektrum Autisme (ASD) pada Balita")

    # Load model
    model_data = load_model()

    if model_data is None:
        st.error("File model 'svm_model.joblib' tidak ditemukan. Pastikan file tersebut ada di repositori GitHub Anda bersama 'app.py'.")
        return

    # Ekstrak objek yang disimpan
    model = model_data['model']
    le_y = model_data['le_y']
    le_sex = model_data['le_sex']
    le_jaundice = model_data['le_jaundice']
    le_family_asd = model_data['le_family_asd']
    training_columns = model_data['training_columns']

    st.write("Aplikasi ini memprediksi kemungkinan ASD pada balita menggunakan model SVM Linear yang sudah dilatih.")

    # --- UI UNTUK INPUT PENGGUNA ---

    questions = {
        "A1": "Apakah anak Anda melihat Anda ketika Anda memanggil namanya?",
        "A2": "Seberapa mudah bagi Anda untuk mendapatkan kontak mata dengan anak Anda?",
        "A3": "Apakah anak Anda menunjuk untuk menunjukkan bahwa ia menginginkan sesuatu?",
        "A4": "Apakah anak Anda menunjuk untuk berbagi minat dengan Anda?",
        "A5": "Apakah anak Anda berpura-pura (misalnya, merawat boneka)?",
        "A6": "Apakah anak Anda mengikuti ke mana Anda melihat?",
        "A7": "Jika Anda sedih, apakah anak Anda menunjukkan tanda-tanda ingin menghibur?",
        "A8": "Apakah Anda akan mendeskripsikan kata-kata pertama anak Anda sebagai 'biasa'?",
        "A9": "Apakah anak Anda menggunakan gerakan sederhana (misalnya, melambaikan tangan)?",
        "A10": "Apakah anak Anda menatap ke hal yang tidak ada tanpa tujuan yang jelas?"
    }

    input_data = {}

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Kuesioner (A1-A10)")
        st.write("Jawab 'Ya' (1) atau 'Tidak' (0).")
        options = {"Tidak": 0, "Ya": 1}

        for key, value in questions.items():
            selected_option = st.radio(f"**{key}:** {value}", options.keys(), horizontal=True, key=key)
            input_data[key] = options[selected_option]

    with col2:
        st.subheader("Data Demografis Anak")

        input_data["Age_Mons"] = st.number_input("Usia (dalam bulan)", min_value=12, max_value=36, value=24)

        # Ambil kelas asli dari encoder yang disimpan
        sex_options = le_sex.classes_
        jaundice_options = le_jaundice.classes_
        family_options = le_family_asd.classes_

        # Opsi Etnis dan Pengisi Tes (hardcode dari data Anda, karena tidak disimpan)
        ethnicity_options = [
            'Middle Eastern', 'White European', 'Hispanic', 'Black', 'Asian',
            'South Asian', 'Native Indian', 'Others', 'Latino', 'Mixed', 'Pacifica'
        ]
        tester_options = [
            'Family Member', 'Health Care Professional', 'Self', 'Others'
        ]

        input_data["Sex"] = st.selectbox("Jenis Kelamin", options=sex_options, format_func=lambda x: "Perempuan" if x == 'F' else "Laki-laki")
        input_data["Jaundice"] = st.selectbox("Riwayat Penyakit Kuning (Jaundice)", options=jaundice_options)
        input_data["Family_mem_with_ASD"] = st.selectbox("Riwayat ASD dalam Keluarga", options=family_options)
        input_data["Ethnicity"] = st.selectbox("Etnis", options=ethnicity_options)
        input_data["Who completed the test"] = st.selectbox("Siapa yang Mengisi Tes?", options=tester_options)

    # --- Tombol Prediksi ---
    st.divider()
    if st.button("Prediksi Kemungkinan ASD", type="primary", use_container_width=True):

        # 1. Buat DataFrame dari input
        input_df = pd.DataFrame([input_data])

        # 2. Transformasi fitur biner menggunakan encoder yang di-load
        try:
            input_df['Sex'] = le_sex.transform(input_df['Sex'])
            input_df['Jaundice'] = le_jaundice.transform(input_df['Jaundice'])
            input_df['Family_mem_with_ASD'] = le_family_asd.transform(input_df['Family_mem_with_ASD'])

            # 3. One-Hot Encoding
            input_df_encoded = pd.get_dummies(input_df, columns=["Ethnicity", "Who completed the test"])

            # 4. Align kolom (SANGAT PENTING)
            # Pastikan kolom di input_df sama persis dengan 'training_columns'
            input_df_final = input_df_encoded.reindex(columns=training_columns, fill_value=0)

            # 5. Prediksi
            # Pipeline model sudah termasuk scaler, jadi tidak perlu scale manual
            prediction = model.predict(input_df_final)[0]
            prediction_proba = model.predict_proba(input_df_final)[0]

            # 6. Konversi hasil prediksi (0/1) kembali ke label (No/Yes)
            prediction_label = le_y.inverse_transform([prediction])[0]

            # 7. Tampilkan hasil
            st.subheader("Hasil Prediksi Model (SVM Linear)")

            if prediction_label == "Yes":
                st.error(f"**Prediksi: Terdeteksi Tanda-Tanda ASD ({prediction_label})**", icon="⚠️")
                st.write(f"Model memiliki keyakinan **{prediction_proba[1]:.2%}** bahwa terdapat tanda-tanda ASD.")
            else:
                st.success(f"**Prediksi: Tidak Terdeteksi Tanda-Tanda ASD ({prediction_label})**", icon="✅")
                st.write(f"Model memiliki keyakinan **{prediction_proba[0]:.2%}** bahwa tidak terdapat tanda-tanda ASD.")

            st.bar_chart(pd.DataFrame(prediction_proba, index=le_y.classes_, columns=["Probabilitas"]))

        except Exception as e:
            st.error(f"Terjadi kesalahan saat melakukan prediksi: {e}")
            st.error("Pastikan semua encoder dan kolom sudah sesuai.")

if __name__ == "__main__":
    main()